---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testssl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testssl
    spec:
      containers:
      - name: testssl
        image: tiswanso/sec_testssl:latest
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/certs
          name: istio-certs
      volumes:
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
